## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.3
  - nightly
notifications:
  email: true

matrix:
  allow_failures:
  - julia: nightly

addons:
  apt:
    packages:
      - xvfb
script:
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
